discordScopes:
  - 'identify'
  - 'email'
botPresenceStatus: 'online'
rateLimitWhitelist:
  - '957840712404193290'
  - '1207874300070199356'
trustProxy: 1
session:
  cookieDomain: '.discord.place'
frontendUrl: 'https://discord.place'
backendUrl: 'https://api.discord.place'
cdnUrl: 'https://cdn.discord.place'
emojis:
  loading: '<a:loading:1247786499076915252>'
  checkmark: '<:yes:1226129515718381568>'
  badges:
    moderator: '<:white_moderator:1251538987592712345>'
    premium: '<:white_premium:1251538989312249947>'
    verified: '<:white_verified:1251538990524403793>'
  empty_badge_slot: '<:empty_badge_slot:1251541500282798090>'
port:
  frontend: 3000
  backend: 3001
guildId: '1200254872059121764'
guildInviteUrl: 'discord.gg/dotplace'
permissions:
  canEditProfiles:
    - '957840712404193290'
  canDeleteProfiles:
    - '957840712404193290'
  canDeleteServers:
    - '957840712404193290'
  canDeleteEmojis:
    - '957840712404193290'
  canDeleteBots:
    - '957840712404193290'
  canDeleteReviews:
    - '957840712404193290'
  canDeleteTemplates:
    - '957840712404193290'
  canApproveEmojisRoles:
    - '1206354879321210900'
    - '1206355082883371049'
    - '1238588360193216695'
  canApproveBotsRoles:
    - '1206354879321210900'
    - '1206355082883371049'
    - '1238588360193216695'
  canEditEmojis:
    - '957840712404193290'
  canApproveReviewsRoles:
    - '1206354879321210900'
    - '1206355082883371049'
    - '1238588360193216695'
  canEditServersRoles:
    - '1206354879321210900'
    - '1206355082883371049'
  canEditBotsRoles:
    - '1206354879321210900'
    - '1206355082883371049'
  canViewQuarantinesRoles:
    - '1206032198562742312'
    - '1206354879321210900'
  canCreateQuarantinesRoles:
    - '1206032198562742312'
    - '1206354879321210900'
  canDeleteQuarantines:
    - '957840712404193290'
  canViewDashboardRoles:
    - '1206354879321210900'
    - '1206355082883371049'
    - '1238588360193216695'
  canViewBlockedIps:
    - '957840712404193290'
  canDeleteBlockedIps:
    - '957840712404193290'
  canDeleteBotDeniesRoles:
    - '1206354879321210900'
    - '1206355082883371049'
  canViewTimeoutsRoles:
    - '1206354879321210900'
    - '1206355082883371049'
  canDeleteTimeoutsRoles:
    - '1206354879321210900'
    - '1206355082883371049'
  canApproveTemplatesRoles:
    - '1206354879321210900'
    - '1206355082883371049'
    - '1238588360193216695'
  canSyncLemonSqueezyPlans:
    - '957840712404193290'
  canExecuteEval:
    - '957840712404193290'
  canExecuteFetch:
    - '957840712404193290'
  canVerifyProfilesRoles:
    - '1206354879321210900'
profilesMaxSocialsLength: 8
packagesMaxEmojisLength: 9
packagesMinEmojisLength: 4
serverKeywordsMaxLength: 5
serverKeywordsMaxCharacters: 32
serverDescriptionMaxCharacters: 256
reviewsMaxCharacters: 256
botShortDescriptionMinLength: 16
botShortDescriptionMaxLength: 150
botDescriptionMinLength: 32
botDescriptionMaxLength: 2048
botWebhookTokenMaxLength: 256
templateMaxNameLength: 32
templateMinDescriptionLength: 32
templateMaxDescriptionLength: 256
templateMaxCategoriesLength: 3
botMaxExtraOwners: 4
roles:
  moderator: '1206354879321210900'
  premium: '1252335063123628084'
emojiCategories:
  - 'All'
  - 'Gaming'
  - 'Anime'
  - 'Memes'
  - 'Pepe'
  - 'Pixel Art'
  - 'Cute'
  - 'Logos'
  - 'Utility'
  - 'Other'
  - 'Animated'
serverCategories:
  - 'Gaming'
  - 'Anime'
  - 'Public'
  - 'Community'
  - 'Music'
  - 'Art'
  - 'Programming'
  - 'Science'
  - 'Technology'
  - 'Education'
  - 'Language'
  - 'Other'
botCategories:
  - 'Moderation'
  - 'Utility'
  - 'Fun & Games'
  - 'Music'
  - 'Economy'
  - 'Roleplay'
  - 'Technology'
  - 'Art & Design'
  - 'Virtual Assistants'
  - 'Social Media Integration'
  - 'Anime & Manga'
  - 'Other'
templateCategories: 
  - 'All'
  - 'Chat'
  - 'Design'
  - 'Music'
  - 'Education'
  - 'Gaming'
  - 'Anime'
  - 'Tech'
  - 'Roleplay'
  - 'Event'
  - 'Other'
emojiMaxCategoriesLength: 4
emojiQueueChannelId: '1210805683751223377'
reviewQueueChannelId: '1213842162828054538'
botQueueChannelId: '1236369862259900566'
templateQueueChannelId: '1247743275914366987'
voteLogsChannelId: '1222817883470434304'
templateApplyLogsChannelId: '1247797537780531235'
portalChannelId: '1238654829916585984'
purchasesChannelId: '1254216137684680745'
excludeCollectionsInBackup:
  - 'sessions'
  - 'botdenies'
  - 'botvotetimeouts'
  - 'remindermetadatas'
  - 'reminders'
  - 'servervoteremindermetadas'
  - 'servervotereminders'
  - 'servervotetimeouts'
quarantineTypes:
  - 'USER_ID'
  - 'GUILD_ID'
quarantineRestrictions:
  'PROFILES_CREATE':
    available_to:
      - 'USER_ID'
  'PROFILES_LIKE':
    available_to:
      - 'USER_ID'
  'EMOJIS_CREATE':
    available_to:
      - 'USER_ID'
  'EMOJIS_QUICKLY_UPLOAD':
    available_to:
      - 'USER_ID'
  'SERVERS_CREATE':
    available_to:
      - 'USER_ID'
      - 'GUILD_ID'
  'SERVERS_CREATE_REVIEW':
    available_to:
      - 'USER_ID'
  'SERVERS_VOTE':
    available_to:
      - 'USER_ID'
      - 'GUILD_ID'
  'BOTS_CREATE':
    available_to:
      - 'USER_ID'
  'BOTS_VOTE':
    available_to:
      - 'USER_ID'
  'BOTS_CREATE_REVIEW':
    available_to:
      - 'USER_ID'
  'BOTS_CREATE_API_KEY':
    available_to:
      - 'USER_ID'
  'TEMPLATES_CREATE':
    available_to:
      - 'USER_ID'
  'TEMPLATES_USE':
    available_to:
      - 'USER_ID'
      - 'GUILD_ID'
quarantineLogsChannelId: '1226257480112406599'
customHostnames:
  - 'dsc.wtf'
  - 'dsc.dog'
  - 'dsc.mom'
globalRateLimit:
  maxRequests: 60
  perMinutes: 2
  cleanUpIntervalInMinutes: 2.5
emojisDenyReasons:
  reposted-emoji:
    name: 'Reposted Emoji'
    description: "If the emoji you're submitting is already available on the site, your submission may be declined to avoid duplicates and maintain variety."
  background-transparency:
    name: 'Background Transparency'
    description: 'Emojis should feature a transparent background. Emojis with opaque backgrounds may not blend well with different message backgrounds and could disrupt visual coherence.'
  whitespace:
    name: 'Whitespace'
    description: 'Emojis containing excess whitespace around the edges may appear disproportionately small when used in messages. To ensure optimal visibility and legibility, please crop your emojis appropriately before submission.'
  incoherent-emoji-package-content:
    name: 'Incoherent Emoji Package Content'
    description: 'Emojis within a package must be compatible with each other to ensure coherence and meaningful usage.'
  offensive-or-inappropriate-content:
    name: 'Offensive or Inappropriate Content'
    description: 'Emojis depicting offensive, inappropriate, or sensitive content such as violence, hate speech, nudity, or discrimination will not be accepted. Keep submissions suitable for a wide audience and respectful of diverse backgrounds and cultures.'
  copyright-infringement:
    name: 'Copyright Infringement'
    description: 'Ensure that your emoji submissions do not violate any copyright or intellectual property rights. Avoid using copyrighted characters, logos, or designs without proper authorization.'
  clear-representation:
    name: 'Clear Representation'
    description: 'Emojis should clearly represent their intended concept or object. Avoid submitting emojis that are overly abstract or ambiguous, as they may cause confusion or misinterpretation among users.'
botsDenyReasons:
  reposted-bot:
    name: 'Reposted Bot'
    description: "If the bot you're submitting is already available on the site, your submission may be declined to avoid duplicates and maintain variety."
  offensive-or-inappropriate-content:
    name: 'Offensive or Inappropriate Content'
    description: 'Bots depicting offensive, inappropriate, or sensitive content such as violence, hate speech, nudity, or discrimination will not be accepted. Keep submissions suitable for a wide audience and respectful of diverse backgrounds and cultures.'
  against-discord-terms-of-service:
    name: 'Against Discord Terms of Service'
    description: "Bots that violate Discord's Terms of Service will not be accepted."
  not-online-or-inviteable:
    name: 'Not Online or Inviteable'
    description: 'Bots must be online and inviteable for usage.'
  base-functionality-is-broken:
    name: 'Base Functionality is Broken'
    description: 'Bots must have functional base features to be considered.'
  copied-bot:
    name: 'Copied Bot'
    description: 'Bots that are direct copies of existing bots will not be accepted.'
  has-vulnerability:
    name: 'Has Vulnerability'
    description: 'Bots with security vulnerabilities will not be accepted.'
  support-for-slash-commands:
    name: 'Support for Slash Commands'
    description: 'Bots must support slash commands for improved user experience and functionality.'
  misleading-or-inaccurate-information:
    name: 'Misleading or Inaccurate Information'
    description: "Bot with misleading descriptions or information may be removed. Provide clear and accurate details about your bot's purpose and content."
templateDenyReasons:
  duplicate-template:
    name: 'Duplicate Template'
    description: "If the template you're submitting is already available on the site, your submission may be declined to avoid duplicates and maintain variety."
  offensive-or-inappropriate-content:
    name: 'Offensive or Inappropriate Content'
    description: 'Templates featuring offensive, inappropriate, or sensitive content such as violence, hate speech, nudity, or discrimination will not be accepted. Ensure your template is suitable for a wide audience and respectful of diverse backgrounds and cultures.'
  against-discord-terms-of-service:
    name: 'Against Discord Terms of Service'
    description: "Templates that violate Discord's Terms of Service will not be accepted."
  poor-quality-or-incomplete-template:
    name: 'Poor Quality or Incomplete Template'
    description: 'Templates should be well-organized and complete. Submissions with poor structure, missing key elements, or that are not user-friendly may be rejected.'
  misleading-or-inaccurate-information:
    name: 'Misleading or Inaccurate Information'
    description: "Templates with misleading titles, descriptions, or information may be rejected. Provide clear and accurate details about your template's purpose and features."
  lacks-clear-focus-or-purpose:
    name: 'Lacks Clear Focus or Purpose'
    description: 'Templates should have a clear focus or purpose. Submissions that are overly broad or lack a specific theme may not be accepted.'
  advertising-and-self-promotion:
    name: 'Advertising and Self-Promotion'
    description: 'Templates primarily focused on advertising or self-promotion without providing genuine value to users may not be accepted.'
  quality-and-presentation:
    name: 'Quality and Presentation'
    description: 'Templates should be well-organized and present a professional appearance. Low-quality or poorly managed templates may not be accepted.'
  proper-categorization:
    name: 'Proper Categorization'
    description: 'Ensure your template is categorized correctly. Misleading categorization can result in rejection.'
instatus:
  page_id: 'clwx1az6k27335bhobasj52b6y'
  metric_id: 'clwx1tevy38905bhobroucjm8j'
lemonSqueezy:
  variantIds:
    tripledVotes:
      servers: '421124'
      bots: '421125'
    standedOut:
      servers: '425991'
      bots: '425992'