name: Greetings

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  greetings:
    name: Greetings
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          pr-message: |-
            Hey there, Pull Request Pioneer! ğŸš€ 

            A big round of applause for stepping into the ring with your very first Pull Request! Thanks a bunch for showing Ivy some love! ğŸ‰

            Just a friendly heads-up:
            - We're all about keeping things cozy here, so feel free to ask questions, share ideas, and make yourself at home! ğŸ 
            - If you're feeling lost or need a little guidance, don't hesitate to reach out. We're all in this together! ğŸ¤